<a href="https://colab.research.google.com/github/notfawadmir/Numpy-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5],dtype='int16')
a

array([1, 2, 3, 4, 5], dtype=int16)

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
b=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]


**Get** **Dimensions**

In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

**Get** **Shape**

In [ ]:
a.shape

(5,)

In [ ]:
b.shape
#(rows,columns)

(2, 5)

**Get** **Type**

In [ ]:
a.dtype

dtype('int16')

**Get** **Size**

In [ ]:
#itemsize in bytes
a.itemsize

2

In [ ]:
Total_size = a.itemsize * a.size
# or
a.nbytes


10

# **Accessing/Changing Specific Row/Column**

In [ ]:
A=np.array([[1,2,3,4,5,6,7,8,9],[6,7,8,9,0,12,4,45,56]])
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 6,  7,  8,  9,  0, 12,  4, 45, 56]])

In [ ]:
#To access a specific element
#e.g I want To Access The 4th Element in the 2 row

A[1][3]
#OR
A[1,3]


9

In [ ]:
#Getting A Specific Row

A[0 , : ]
# OR
A[0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Getting a Specific Column
A[ :, 3]

array([4, 9])

In [ ]:
#Slicing By Index

A[0, 3:9:2 ]
#OR
A[0,3:-1:2]

array([4, 6, 8])

In [ ]:
#changing value of an element

A[1,5]=2900
print(A)

[[   1    2    3    4    5    6    7    8    9]
 [   6    7    8    9    0 2900    4   45   56]]


In [ ]:
A[:,4]=5
A

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9],
       [   6,    7,    8,    9,    5, 2900,    4,   45,   56]])

In [ ]:
A[:,3]=[0,0]
A

array([[   1,    2,    3,    0,    5,    6,    7,    8,    9],
       [   6,    7,    8,    0,    5, 2900,    4,   45,   56]])

In [ ]:
# 3-D Array

B=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(B)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# 2nd element of 2nd row
B[0,1,1]

5

In [ ]:
# 2nd element of 2nd row of 2nd 2-D Array
B[1,1,1]

11

In [ ]:
B[:,:,2]

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
B[0,1,:]

array([4, 5, 6])

In [ ]:
B[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Replace

B[0,:,:]=7
print(B)

[[[ 7  7  7]
  [ 7  7  7]]

 [[ 7  8  9]
  [10 11 12]]]


# **Initializing Different Types Of Arrays**

In [ ]:
#zeros

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,4),dtype='int16')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [ ]:
#ones
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
#Full
np.full([2,2],99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(B,1)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [ ]:
np.full(B.shape,7)

array([[[7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7]]])

In [ ]:
#Random Float Number

np.random.rand(2,2)

array([[0.74391777, 0.81959234],
       [0.73090176, 0.1464084 ]])

In [ ]:
np.random.random_sample(B.shape)

array([[[0.56246118, 0.68810876, 0.34207392],
        [0.63086064, 0.96578733, 0.03470267]],

       [[0.86519646, 0.53093871, 0.20342496],
        [0.15516834, 0.14948203, 0.82793172]]])

In [ ]:
#Random Int Number

np.random.randint(0,7, size=(3,3))

array([[4, 6, 2],
       [3, 3, 6],
       [5, 3, 2]])

In [ ]:
#identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Repeat
a=np.array([[1,2,3]])
np.repeat(a,3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
[1,1,1,1,1]
[1,0,0,0,1]
[1,0,9,0,1]
[1,0,0,0,1]
[1,1,1,1,1]



[1, 1, 1, 1, 1]

In [ ]:
a=np.zeros([5,5],dtype='int16')
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
# a[:1]=1
a[0:1]=1
a[:,0]=1
a[4:5]=1
a[:,4]=1
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
a[2,2]=9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#another way

a=np.ones([5,5])
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z=np.zeros((3,3))
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [ ]:
a[1:4,1:4]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# **Axis**

In [ ]:
A=np.array([1,2,3,4,5])
#It Has Only 1 Axis that is 1
print(A,axis=0)

TypeError: 'axis' is an invalid keyword argument for print()

# Copying array

In [ ]:
#by simply making b=a, changes made in b will also be implemented on a.
a=np.array([1,2,3])
b=a
print(b)

[1 2 3]


In [ ]:
b[0]=20
print(b)

[20  2  3]


In [ ]:
print(a)

[20  2  3]


In [ ]:
a=np.array([1,2,3])
b=a.copy()
print(b)

[1 2 3]


# Mathematics

In [ ]:
A=np.array([1,2,3,4])

In [ ]:
A+2

array([3, 4, 5, 6])

In [ ]:
A-2

array([-1,  0,  1,  2])

In [ ]:
A*2

array([2, 4, 6, 8])

In [ ]:
A/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
A+=2
print(A)

[3 4 5 6]


In [ ]:
B=np.array([1,2,3,4])
A+B

array([2, 4, 6, 8])

In [ ]:
#trignometric functions

np.cos(A)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [ ]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(a)
print(b)

c=np.matmul(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [ ]:
#To Find The Determinant

c=np.identity(3)
np.linalg.det(c)


1.0

# Statistics

In [ ]:
stats=np.array([[1,2,3,4,5],[6,7,8,9,0]])
stats

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [ ]:
np.min(stats)

0

In [ ]:
np.max(stats,axis=0)

array([6, 7, 8, 9, 5])

In [ ]:
np.sum(stats,axis=1)

array([15, 30])

# **zxczxczxc**